<a href="https://colab.research.google.com/github/DENGCPU/PyTorch-Study/blob/main/PyTorch%E8%87%AA%E5%8A%A8%E5%BE%AE%E5%88%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# 设置 requires_grad=True 来跟踪与张量相关的计算
x = torch.ones(2,2,requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [2]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
# 每个张量都有一个 .grad_fn 属性保存着创建了张量的 Function 的引用
print(y.grad_fn)

In [5]:
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [7]:
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print('初始值：', a.requires_grad)
#.requires_grad_( ... ) 会改变张量的 requires_grad 标记
a.requires_grad_(True)
print('改变后值：',a.requires_grad)

初始值： False
改变后值： True


In [8]:
# 梯度

#后向传播，out是标量，out.backward() 等同于out.backward(torch.tensor(1.))。
out.backward()
# 打印梯度 d(out(x))/dx
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [9]:
# 雅克比向量积
x= torch.randn(3, requires_grad=True)
y = x * 2

while y.data.norm() < 1000:
  y = y * 2

print(y)

tensor([ 742.0190, 1043.9253, 1067.2874], grad_fn=<MulBackward0>)


In [10]:
v = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [11]:
# 代码包裹在 with torch.no_grad()，来停止对从跟踪历史中 的 .requires_grad=True 的张量自动求导
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
  print((x ** 2).requires_grad)

True
True
False
