<a href="https://colab.research.google.com/github/DENGCPU/PyTorch-Study/blob/main/PyTorch%E5%85%A5%E9%97%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Tensors(张量)
# 类似于Numpy的ndarrays，同时可以使用GPU计算

In [ ]:
from __future__ import print_function
import torch

x = torch.empty(5,3)
print(x)

tensor([[8.3959e-33, 1.3563e-19, 2.8624e+20],
        [6.9785e+22, 6.6554e-33, 1.3563e-19],
        [1.3563e-19, 1.6114e-19, 1.8308e+22],
        [7.2131e+22, 1.5793e-19, 5.2968e+10],
        [3.3646e+03, 1.7730e+28, 3.5606e+09]])


In [ ]:
# 构造一个随机初始化矩阵
x =  torch.rand(5,3)
print(x)

tensor([[0.5516, 0.2178, 0.2251],
        [0.8171, 0.5019, 0.3120],
        [0.8913, 0.9759, 0.6535],
        [0.0100, 0.2018, 0.1359],
        [0.5960, 0.3069, 0.2796]])


In [ ]:
# 构造一个全是0，数据类型是long的矩阵
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
# 构造一个张量，直接使用数据
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [ ]:
# 创建一个tensor基于已经存在的tensor
x = x.new_ones(5,3,dtype=torch.double)
print('x1:',x)

x = torch.randn_like(x,dtype=torch.float)
print('x2:',x)

x1: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
x2: tensor([[ 0.5277, -1.1387, -0.3982],
        [ 0.2126, -0.8091, -0.4495],
        [ 0.0756,  0.8445,  0.2179],
        [-1.0429,  0.3254,  0.2047],
        [-1.3147, -0.1560, -0.8318]])


In [ ]:
# 获取维度信息
print(x.size())

torch.Size([5, 3])


In [ ]:
# 加法操作

# 方法1
y = torch.rand(5,3)
print('x',x)
print('y',y)
print('x+y',x+y)

x tensor([[ 0.5277, -1.1387, -0.3982],
        [ 0.2126, -0.8091, -0.4495],
        [ 0.0756,  0.8445,  0.2179],
        [-1.0429,  0.3254,  0.2047],
        [-1.3147, -0.1560, -0.8318]])
y tensor([[0.7805, 0.2703, 0.1345],
        [0.6806, 0.6618, 0.9375],
        [0.0777, 0.6442, 0.1281],
        [0.2959, 0.4272, 0.5476],
        [0.5125, 0.1833, 0.1920]])
x+y tensor([[ 1.3083, -0.8684, -0.2637],
        [ 0.8932, -0.1473,  0.4880],
        [ 0.1533,  1.4887,  0.3461],
        [-0.7469,  0.7526,  0.7523],
        [-0.8021,  0.0272, -0.6398]])


In [ ]:
# 方法2
print(torch.add(x,y))

tensor([[ 1.3083, -0.8684, -0.2637],
        [ 0.8932, -0.1473,  0.4880],
        [ 0.1533,  1.4887,  0.3461],
        [-0.7469,  0.7526,  0.7523],
        [-0.8021,  0.0272, -0.6398]])


In [ ]:
# 方法3
result =  torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 1.3083, -0.8684, -0.2637],
        [ 0.8932, -0.1473,  0.4880],
        [ 0.1533,  1.4887,  0.3461],
        [-0.7469,  0.7526,  0.7523],
        [-0.8021,  0.0272, -0.6398]])


In [ ]:
# 方法4
# add x to y
y.add_(x)
print('x',x)
print('y',y)

x tensor([[ 0.5277, -1.1387, -0.3982],
        [ 0.2126, -0.8091, -0.4495],
        [ 0.0756,  0.8445,  0.2179],
        [-1.0429,  0.3254,  0.2047],
        [-1.3147, -0.1560, -0.8318]])
y tensor([[ 1.3083, -0.8684, -0.2637],
        [ 0.8932, -0.1473,  0.4880],
        [ 0.1533,  1.4887,  0.3461],
        [-0.7469,  0.7526,  0.7523],
        [-0.8021,  0.0272, -0.6398]])


In [ ]:
# 索引操作
print(x[:,1])

tensor([-1.1387, -0.8091,  0.8445,  0.3254, -0.1560])


In [ ]:
# 改变大小
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # the size -1 is inferred from other dimensions
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [ ]:
# 使用.item()获得张量的value
x= torch.randn(1)
print(x)
print(x.item())

tensor([-0.4315])
-0.4314519762992859
